# infra/airflow-values.yaml
images:
  airflow:
    repository: apache/airflow
    tag: 2.8.1-python3.11

# Sử dụng kiến trúc Executor đơn giản để tiết kiệm RAM/CPU trên AKS
core:
  executor: LocalExecutor

# Cấu hình Webserver công khai để bạn mở giao diện trên trình duyệt khi Demo
webserver:
  service:
    type: LoadBalancer
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"

postgresql:
  enabled: true
  architecture: standalone

# Mount file DAG từ ConfigMap để không cần GitHub auth
extraConfigmapMounts:
  - name: oulad-medallion-dag
    mountPath: /opt/airflow/dags/oulad_medallion_dag.py
    configMap: oulad-medallion-dag
    subPath: oulad_medallion_dag.py
    readOnly: true
