apiVersion: apps/v1
kind: Deployment
metadata:
  name: blearn-api-gateway
  namespace: blearn-medallion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: acrblearnminh2026.azurecr.io/oulad-medallion:latest
        imagePullPolicy: Always
        command: ["python", "backend-api/serving_gateway.py"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "250m"
            memory: "1Gi"
        env:
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: oulad-runtime
              key: AZURE_STORAGE_ACCOUNT
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: oulad-runtime
              key: AZURE_STORAGE_KEY
        - name: REDIS_HOST
          value: "redis-service.blearn-medallion.svc.cluster.local"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service.blearn-medallion.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "learning-events"
---
apiVersion: v1
kind: Service
metadata:
  name: blearn-api-service-gateway
  namespace: blearn-medallion
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: api-gateway
